// apps/zhi-server-vue3-ssr/layouts/vdoing.vue
<!--
  - Copyright (c) 2023, Terwer . All rights reserved.
  - DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  -
  - This code is free software; you can redistribute it and/or modify it
  - under the terms of the GNU General Public License version 2 only, as
  - published by the Free Software Foundation.  Terwer designates this
  - particular file as subject to the "Classpath" exception as provided
  - by Terwer in the LICENSE file that accompanied this code.
  -
  - This code is distributed in the hope that it will be useful, but WITHOUT
  - ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  - FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
  - version 2 for more details (a copy is included in the LICENSE file that
  - accompanied this code).
  -
  - You should have received a copy of the GNU General Public License version
  - 2 along with this work; if not, write to the Free Software Foundation,
  - Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
  -
  - Please contact Terwer, Shenzhen, Guangdong, China, youweics@163.com
  - or visit www.terwer.space if you need additional information or have any
  - questions.
  -->

<template>
  <div class="theme-container">
    <!-- 页眉 -->
    <header>
      <Navbar />
      <div class="head-placeholder"></div>
    </header>

    <!-- 正文 -->
    <div class="content-main">
      <slot />
    </div>

    <!-- 页脚 -->
    <footer>
      <h1>This is the footer</h1>
    </footer>
  </div>
</template>

<script lang="ts" setup>
// 主题样式注入入口
import "../assets/vdoing/fonts/webfont.css"
import "../assets/vdoing/styles/index.styl"

import Navbar from "~/components/vdoing/Navbar.vue"
</script>

<style lang="stylus">
@require "../assets/vdoing/styles/index"

.head-placeholder
  height 60px

.custom-html-window
  position fixed
  bottom 0
  display flex
  overflow hidden
  font-weight 350
  @media (max-width 960px)
    display none
  .custom-wrapper
    position relative
    max-width 200px
    max-height 400px
    .close-but
      cursor pointer
      position absolute
      right 0
      top 0
      font-size 1.5rem
      line-height 1.5rem
      width 1.5rem
      height 1.5rem
      opacity 0
      transition all 0.2s
      &:hover
        opacity 0.9
    &:hover
      .close-but
        opacity 0.7
  &.custom-html-window-lb
    left 0
    z-index 99
    &>*
      align-self flex-end
  &.custom-html-window-rb
    right 80px
    z-index 10
    justify-content flex-end
    &>*
      align-self flex-end
</style>

// apps/zhi-server-custom/src/layouts/vdoing.tsx
/*
 * Copyright (c) 2023, Terwer . All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Terwer designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Terwer in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Terwer, Shenzhen, Guangdong, China, youweics@163.com
 * or visit www.terwer.space if you need additional information or have any
 * questions.
 */

import React from "react"

// 主题样式注入入口
import "../assets/vdoing/fonts/webfont.css"
import "../assets/vdoing/styles/index.styl"
// 布局样式
import "./vdoing.styl"
import Navbar from "../components/vdoing/Navbar"

type VdoingLayoutProps = {
  header: React.ReactNode
  main: React.ReactNode
  footer: React.ReactNode
  props?: Record<string, any>
}

/**
 * Vdoing 布局
 *
 * @param header - 头部
 * @param main - 正文
 * @param footer - 底部
 * @param props - 参数
 * @author terwer
 * @version 1.0.0
 * @since 1.0.0
 * @constructor
 */
const VdoingLayout: React.FC<VdoingLayoutProps> = ({ header, main, footer, props }) => {
  return (
    <div className={"theme-container"}>
      <header>
        <Navbar />
        <div className={"head-placeholder"}></div>
        {header}
      </header>
      <main className={"content-main"}>{main}</main>
      <footer>
        <h1>This is the footer</h1>
        {footer}
      </footer>
    </div>
  )
}

export default VdoingLayout
